#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision-upi-infra | Build Infra Resources'
  hosts: local
  #hosts: localhost
  vars:
    module: "provision-ovirt"
    state_provider: "local"
    tf_module_path: "{{ dir_terraform }}/ovirt"
    ansible_name_module: " Konductor | Build UPI Infra Resources | {{ module }}"
  vars_files:
    - vars/global.yml

  pre_tasks:
    #- name: Ensure the right version of python is installed on host
    #  become: true
    #  yum:
    #    name: python2-jmespath
    #    state: present

  tasks:
  roles:
    - build-upi-infra-resources 
