#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra  | loadbalancer.yml' 
  hosts: newlb
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "loadbalancer"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:
    - name: '{{ ansible_name_module }} | Install and configure LB'
      when: 
        - provision_lb is defined
        - provision_lb | bool
      block:
        - name: '{{ ansible_name_module }} | Import LB installation role'
          import_role:
            name: loadbalancer
          register: lb_installed

        - name: '{{ ansible_name_module }} | copy LB config template into place'
          template:
            src: ./templates/haproxy.cfg.j2
            dest: /etc/haproxy/haproxy.cfg
          register: haproxycfg_copied

        - name: '{{ ansible_name_module }} | Ensure the firewall-cmd is installed'
          yum:
            name: "firewalld,python-firewall"
          register: firewalld_pkgs_installed

        - name: '{{ ansible_name_module }} | Ensure Firewalld is enabled'
          systemd:
            name: firewalld
            state: started
            enabled: yes

        - name: '{{ ansible_name_module }} | Enable appropriates port on public zone'
          firewalld:
            port: "{{ item }}"
            permanent: yes
            zone: public
            immediate: yes
            state: yes
          loop:
            - 6443/tcp
            - 22623/tcp
            - 443/tcp

        - name: '{{ ansible_name_module }} | Enable appropriates port on internal zone'
          firewalld:
            port: "{{ item }}"
            permanent: yes
            zone: internal
            immediate: yes
            state: yes
          loop:
            - 6443/tcp
            - 22623/tcp
            - 443/tcp

        - name: '{{ ansible_name_module }} | Restart the HAProxy service'
          systemd:
            name: haproxy
            state: restarted

