#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra | publish-ignition.yml' 
  hosts: "{{ nginx_hosts | default(groups.newregistry) }}"
  become: yes
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "registry"
    ansible_name_module: " Konductor | Provision UPI Infra | {{ module }}"
    host_rhcos_images: false
  tasks:
    - name: '{{ ansible_name_module }} | file:absent | remove existing ignition files from web server '
      file: 
        path: "{{ nginx_root_directory }}/{{ ign_repos_name }}/{{ item }}"
        state: absent
      loop:
        - bootstrap.ign
        - master.ign
        - worker.ign

    - name: '{{ ansible_name_module }} | copy ignition files to web server '
      copy:
        src: "{{ dir_deploy }}/nginx/{{ item }}"
        dest: "{{ nginx_root_directory }}/{{ ign_repos_name }}/{{ item }}"
        mode: 0777
        force: yes
      loop:
        - bootstrap.ign
        - master.ign
        - worker.ign

    - name: '{{ ansible_name_module }} | copy image files to web server '
      copy:
        src: "{{ dir_deploy }}/nginx-images/{{ item }}"
        dest: "{{ nginx_root_directory }}/{{ ign_repos_name }}/{{ item }}"
        mode: 0777
        force: yes
      loop:
        - "{{ rhcos_image_iso_name }}"
        #- "{{ rhcos_image_raw_name }}"
      when:
        - host_rhcos_images is defined
        - host_rhcos_images | bool 
