#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra | Gather instance facts'
  hosts: local
  #hosts: localhost
  gather_facts: no
  tasks:
    - setup:

- name: ' Konductor | Provision UPI Infra | Build Ovirt Nodes'
  hosts: localhost
  vars:
    module: "ovirt"
    state_provider: "local"
    tf_module_path: "{{ dir_terraform }}/{{ module }}"
    ansible_name_module: " Konductor | Provision UPI Infra | {{ module }}"
  vars_files:
    - vars/global.yml
  roles:
    - setup-terraform-module
