---
# tasks file for setup-terraform-module

- name: '{{ ansible_name_module }} | add_host | import_tasks vm.yml'
  import_tasks: vm.yml
  when: 
    - use_vm_tasks is defined
    - use_vm_tasks | bool 

- name: '{{ ansible_name_module }} | add_host | import_tasks vms-and-disks.yml'
  import_tasks: vms-and-disks.yml 
  when: 
    - not use_vm_tasks is defined or ( not use_vm_tasks | bool)

